### ISSUE TITLE
How long are images cached for?

### ISSUE THREAD

**Issue by OtakuEmily** [cardboard-ink/PhotoBox#1]
Hiya, just making this issue to ask how long images are cached for.

**Comment by sosweetham** [comment]
> Hiya, just making this issue to ask how long images are cached for.

If the image is not present in the cache at the time of request, it is fetched directly from Guilded at that moment. If it is present and it is 24 hours older, you are sent the most recent cache at that moment while the server updates it, subsequent requests give the updated image. 

Tldr; 
they are cached for 24 hours until an update is performed

**Comment by OtakuEmily** [comment]
Ah k, thanks!

(Edited to remove DuckDuck's spammy headers)
